# Generated by Django 3.0.4 on 2020-04-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmanager',
            name='phone',
        ),
        migrations.AddField(
            model_name='carmanager',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='phone1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='phone2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='phone3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carmanager',
            name='tg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
